name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Replace with the specific Python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: |
          coverage run --source=calculator -m pytest
          coverage xml

      - name: Set UTF-8 Encoding
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: 887556e2b289447dbb940a281210aee8
          coverage-reports: coverage.xml  # Specify the XML coverage report file explicitly
