name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Set UTF-8 Encoding
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: 887556e2b289447dbb940a281210aee8
          coverage-reports: .coverage  # Specify the coverage report file explicitly
          # or a comma-separated list for multiple reports
          # coverage-reports: .coverage,other_report.xml
